# Generated by Django 5.0.1 on 2024-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_by',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
